/** Teaching text for each evolution stage, keyed by STAGES[].key. */
export const STAGE_INFO = {
  genesis: {
    tagline: 'Novel and uncertain',
    definition: 'Something new that has barely been tried. It is poorly understood, changes constantly, and nobody is sure yet what it is good for.',
    traits: ['Rare, risky and exciting', 'Experimental, with frequent failure', 'Uncertain future and value'],
    examples: 'A research idea, an unproven prototype',
    insight: 'Learn by experimenting. Invest small, measure, and do not plan far ahead. A roadmap is the wrong tool here.',
  },
  custom: {
    tagline: 'Built for you',
    definition: 'Understood well enough to build, but each one is made by hand for a particular customer or purpose.',
    traits: ['Bespoke: no two are the same', 'Learning quickly, mostly by doing', 'Expensive, but can set you apart while it is rare'],
    examples: 'A bespoke booking system, a one-off custom-built kettle',
    insight: 'Treat it as craft: iterate closely with the people who use it. It can give you an edge, but others will copy it and it will drift to the right.',
  },
  product: {
    tagline: 'Off the shelf',
    definition: 'Many suppliers sell similar ready-made versions that compete on features. It is well understood and improves in steady steps.',
    traits: ['Compared on features and price', 'Bought or rented, not built', 'Growing, increasingly familiar market'],
    examples: 'Packaged software, a retail kettle, a cup of tea in a cafe',
    insight: 'Buy rather than build. Compare suppliers, and plan for it to become a commodity.',
  },
  commodity: {
    tagline: 'Standard and interchangeable',
    definition: 'Standardised and widely available, often sold as a metered service. The differences between suppliers barely matter.',
    traits: ['Ubiquitous and fit for purpose', 'Competes on price, volume and reliability', 'Rarely a source of advantage by itself'],
    examples: 'Electricity, cloud computing, standard tea bags',
    insight: 'Use it as a service and never build your own. The opportunity is in what you build on top of it.',
  },
};

/** Help text for axis titles and map marks (inertia), keyed by the `data-help` value on the label. */
export const HELP_INFO = {
  visible: {
    title: 'Visible',
    tagline: 'What the user can see and ask for',
    definition: 'Components near the top are things the user directly experiences or asks for: the need itself. If they would notice it missing straight away, it belongs high up.',
    traits: ['Closest to the user and their needs', 'The user can describe it in their own words', 'The part of the service they judge you on'],
    facts: [['Insight', 'Always start here. Put the user at the top, then work downwards.']],
  },
  invisible: {
    title: 'Invisible',
    tagline: 'What the user never sees',
    definition: 'Components near the bottom are the supporting infrastructure the user never sees or thinks about, although they depend on it completely.',
    traits: ['Hidden behind the service', 'Taken for granted until it fails', 'Often shared with many other services'],
    facts: [['Examples', 'Electricity, networks, raw materials'], ['Insight', 'Keep asking "what does this need?" until you reach things so ordinary that nobody thinks about them.']],
  },
  'value-chain': {
    title: 'Value Chain',
    tagline: 'How needs depend on each other',
    definition: 'The vertical axis orders components by how visible they are to the user. A line from one component down to another means the upper one depends on the lower one.',
    traits: ['Top: the user and their needs', 'Each line means "depends on"', 'Lower down: the capabilities that deliver the need'],
    facts: [['Example', 'Cup of tea needs a kettle, which needs power.'], ['Insight', 'Build the chain first and ignore left and right. Ask "what does the user need?", then keep asking "what does that need?". Only then place each part along the evolution axis.']],
  },
  evolution: {
    title: 'Evolution',
    tagline: 'How mature each part is',
    definition: 'The horizontal axis shows how evolved a component is, from brand new on the left to standardised on the right. It is about how widely the thing is understood and supplied, not about the date.',
    traits: ['Parts drift right over time as competition and demand grow', 'Four stages: hover a stage label for details'],
    facts: [['Insight', 'For each part ask: is it new, built to order, bought as a product, or a standard utility? Each stage calls for a different way of working.']],
  },
  inertia: {
    title: 'Inertia',
    tagline: 'Resistance to change',
    definition: 'Something that slows or blocks a component from evolving, even though competition and demand are pushing it to the right. It is drawn as a bar in the path of the component.',
    traits: ['Existing investment, skills or contracts', 'Habit, culture and fear of losing what works today', 'Often strongest where the old way still makes money'],
    facts: [['Example', 'A company with its own data centre resists moving to cloud services.'], ['Insight', 'A component with inertia will move later than the market, so competitors without it can overtake you. Plan how to reduce it (retrain, change incentives) rather than ignore it.']],
  },
  pipeline: {
    title: 'Pipeline',
    tagline: 'A component with several variants',
    definition: 'Some components exist as a range of similar variants, each at its own stage of evolution, such as different kinds of kettle. The box groups the variants, which are spread along the evolution axis at one level of the value chain.',
    traits: ['Variants differ in maturity, not in the need they serve', 'New variants appear on the left and older ones drift right', 'The component that owns the pipeline sits just above the box'],
    facts: [['Example', 'Kettles: stove-top, electric, smart.'], ['Insight', 'Read the box from both ends. The right shows what is becoming standard, and the left shows what is about to arrive.']],
  },
  build: {
    title: 'Build',
    tagline: 'Make it ourselves',
    definition: 'We create and run this component ourselves. It is shown with a dashed ring.',
    traits: ['Full control, full responsibility', 'Needs skills and time to maintain', 'Sensible when it is new or sets you apart'],
    facts: [['Insight', 'Build things in Genesis or Custom Built where doing it yourself can create an advantage. Building something that is already a commodity usually wastes effort.']],
  },
  buy: {
    title: 'Buy',
    tagline: 'Purchase a product',
    definition: 'We buy a ready-made product and run it ourselves or configure it. It is shown with a grey ring.',
    traits: ['Faster than building', 'Several suppliers compete on features', 'Some customising, but you follow the supplier'],
    facts: [['Insight', 'This is the natural choice for components in the Product stage. Compare suppliers, and expect them to become commodities in time.']],
  },
  outsource: {
    title: 'Outsource',
    tagline: 'Have someone else run it',
    definition: 'Another party delivers this component as a service and runs it for us. It is shown with a solid dark ring.',
    traits: ['Pay for use rather than own', 'Suppliers handle the operation', 'Little room to customise'],
    facts: [['Insight', 'Best for commodities and utilities. Spend your own effort on the parts that make you different.']],
  },
  need: {
    title: 'User need',
    tagline: 'What the user wants',
    definition: 'A need is something a user wants, described from their side rather than in terms of how it is delivered. It belongs at the top of the value chain, drawn as a square.',
    traits: ['Stated in the words of the user', 'Delivered by the capabilities beneath it', 'Needs evolve too, as expectations rise'],
    facts: [['Example', 'A cup of tea, or fast checkout.'], ['Insight', 'Start with the need, not the technology. If you cannot name the user who has it, question whether it belongs on the map.']],
  },
  practice: {
    title: 'Practice',
    tagline: 'A way of working',
    definition: 'How something is done rather than a thing that is used: a method, habit or approach. Practices evolve from novel ideas to widely accepted good practice. They are drawn as triangles.',
    traits: ['Spreads between organisations as it proves useful', 'Needs people to change how they work', 'Often held back by inertia'],
    facts: [['Example', 'Agile delivery, or brewing tea by the pot.'], ['Insight', 'A practice that is already standard is not a source of advantage. Being early with a good one can be.']],
  },
  data: {
    title: 'Data',
    tagline: 'Information that is held and used',
    definition: 'The information a component creates, stores or relies on. It is drawn as a hexagon.',
    traits: ['Moves from unmodelled, to modelled, to widely shared standards', 'Its value comes from what it is used for', 'Shared data tends to commoditise'],
    facts: [['Example', 'Order history or a customer list.'], ['Insight', 'Ask who needs the data and how standard it is. Standard data is easy to exchange and hard to protect.']],
  },
  knowledge: {
    title: 'Knowledge',
    tagline: 'What people understand',
    definition: 'What people know about how something works or should be done. It is drawn as a diamond.',
    traits: ['Held by people and written down only in part', 'Moves from concept, to hypothesis, to theory, to accepted fact', 'Spreads with education and experience'],
    facts: [['Example', 'Knowing how to blend tea, or recognising fraud.'], ['Insight', 'Where knowledge is thin, expect to learn by trying things. Where it is well established, buy it in.']],
  },
  market: {
    title: 'Market',
    tagline: 'Many buyers and many sellers',
    definition: 'A component that is traded among many consumers and many providers. It is drawn as a circle holding a small network of dots.',
    traits: ['Suppliers compete, so prices fall', 'Buyers can switch supplier fairly easily', 'Usually found at the commodity end'],
    facts: [['Example', 'Payment providers, or tea auctions.'], ['Insight', 'When a market forms you can stop building and choose between suppliers. Shape your needs so that you can switch.']],
  },
  ecosystem: {
    title: 'Ecosystem',
    tagline: 'A community that grows around a component',
    definition: 'Other people build, sell and extend things around a component, which makes it more valuable the more of them there are. It is drawn as a dashed ring with satellites.',
    traits: ['Value grows with the number of participants', 'Hard for newcomers to match', 'Needs looking after: the owner sets the rules'],
    facts: [['Example', 'An app marketplace or a plugin community.'], ['Insight', 'Watch what the community builds: it shows which parts of your component are about to become commodities.']],
  },
};
